name       : make
version    : 4.2.1
release    : 6
source     :
    - http://ftp.gnu.org/gnu/make/make-4.2.1.tar.gz : e40b8f018c1da64edd1cc9a6fce5fa63b2e707e404e20cad91fbae337c98a5b7
homepage   : http://www.gnu.org/software/make/
license    :
    - GPL-2.0
summary    : Tool to compile sources trees
component  : system.devel
patterns   :
    - /usr/include
description: |
    Make is a tool which controls the generation of executables and other non-source files of a program from the program's source files.
setup      : |
    %configure --program-prefix=g
build      : |
    %make
install    : |
    %make_install
    ln -sv gmake $installdir/usr/bin/make
