name       : make
version    : '4.3'
release    : 9
source     :
    - https://ftp.gnu.org/gnu/make/make-4.3.tar.gz : e05fdde47c5f7ca45cb697e973894ff4f5d79e13b750ed57d7b66d8defc78e19
homepage   : https://www.gnu.org/software/make/
license    : GPL-3.0-or-later
component  : system.devel
summary    : Tool to compile sources trees
description: |
    Make is a tool which controls the generation of executables and other non-source files of a program from the program's source files.
patterns   :
    - /usr/include
setup      : |
    %configure --program-prefix=g
build      : |
    %make
install    : |
    %make_install
    ln -sv gmake $installdir/usr/bin/make
check      : |
    %make check
