name       : make
version    : '4.4.1'
release    : 10
source     :
    - https://ftp.gnu.org/gnu/make/make-4.4.1.tar.gz : dd16fb1d67bfab79a72f5e8390735c49e3e8e70b4945a15ab1f81ddb78658fb3
homepage   : https://www.gnu.org/software/make/
license    : GPL-3.0-or-later
component  : system.devel
summary    : Tool to compile sources trees
description: |
    Make is a tool which controls the generation of executables and other non-source files of a program from the program's source files.
patterns   :
    - /usr/include
setup      : |
    %configure --program-prefix=g
build      : |
    %make
install    : |
    %make_install
    ln -sv gmake $installdir/usr/bin/make
check      : |
    # Breaks a few tests
    unset LD_PRELOAD

    %make check
