name        : make
version     : 4.1
release     : 4
source      :
    - http://ftp.gnu.org/gnu/make/make-4.1.tar.gz : 9fc7a9783d3d2ea002aa1348f851875a2636116c433677453cc1d1acc3fc4d55
homepage    : http://www.gnu.org/software/make/
license     :
    - GPLv2
summary     : Tool to compile sources trees
patterns    :
    - /usr/include
description : |
    Make is a tool which controls the generation of executables and other non-source files of a program from the program's source files.
setup      : |
    # Fix segfault without /dev/pts
    %patch -p1 < $pkgfiles/bug43434.patch
    %configure --program-prefix=g
build      : |
    %make
install    : |
    %make_install
    ln -sv /usr/bin/gmake $installdir/usr/bin/make
